// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Entities;
namespace Repositories;

public partial class MyShop330683525Context : DbContext
{
    public MyShop330683525Context(DbContextOptions<MyShop330683525Context> options)
        : base(options)
    {
    }
    
    public MyShop330683525Context()
    {

    }

    public virtual DbSet<BasicSite> BasicSites { get; set; }

    public virtual DbSet<CartItem> CartItems { get; set; }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<MainCategory> MainCategories { get; set; }

    public virtual DbSet<Order> Orders { get; set; }

    public virtual DbSet<OrdersItem> OrdersItems { get; set; }

    public virtual DbSet<Platform> Platforms { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<Review> Reviews { get; set; }

    public virtual DbSet<SiteType> SiteTypes { get; set; }

    public virtual DbSet<Status> Statuses { get; set; }

    public virtual DbSet<User> Users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<BasicSite>(entity =>
        {
            entity.HasKey(e => e.BasicSiteId).HasName("PK__BasicSit__FFB1C8E00A0F2A9B");

            entity.Property(e => e.BasicSiteId).HasColumnName("BasicSiteID");
            entity.Property(e => e.SiteName)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.SiteTypeId).HasColumnName("SiteTypeID");
            entity.Property(e => e.UserDescreption)
                .HasMaxLength(500)
                .IsUnicode(false);

            entity.HasOne(d => d.BasicSitesPlatformsNavigation).WithMany(p => p.BasicSites)
                .HasForeignKey(d => d.BasicSitesPlatforms)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__BasicSite__Basic__5DCAEF64");

            entity.HasOne(d => d.SiteType).WithMany(p => p.BasicSites)
                .HasForeignKey(d => d.SiteTypeId)
                .HasConstraintName("FK__BasicSite__SiteT__5CD6CB2B");
        });

        modelBuilder.Entity<CartItem>(entity =>
        {
            entity.HasKey(e => e.CartId).HasName("PK__CartItem__51BCD7976E2737F6");

            entity.Property(e => e.CartId).HasColumnName("CartID");
            entity.Property(e => e.ProductsId).HasColumnName("ProductsID");
            entity.Property(e => e.UserDescription)
                .HasMaxLength(400)
                .IsUnicode(false);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.Valid).HasDefaultValue((byte)1);

            entity.HasOne(d => d.BasicSitesPlatformsNavigation).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.BasicSitesPlatforms)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__Basic__6FE99F9F");

            entity.HasOne(d => d.Products).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.ProductsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__Produ__6E01572D");

            entity.HasOne(d => d.User).WithMany(p => p.CartItems)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__CartItems__UserI__6D0D32F4");
        });

        modelBuilder.Entity<Category>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__Categori__19093A2B64782F10");

            entity.HasIndex(e => e.ImgUrl, "UQ__Categori__1BCAF4FC09985E21").IsUnique();

            entity.HasIndex(e => e.CategoryName, "UQ__Categori__8517B2E0A2ABB83C").IsUnique();

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryDescreption)
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.CategoryPrompt)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.ImgUrl)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.MainCategoryId).HasColumnName("MainCategoryID");

            entity.HasOne(d => d.MainCategory).WithMany(p => p.Categories)
                .HasForeignKey(d => d.MainCategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Categorie__MainC__4E88ABD4");
        });

        modelBuilder.Entity<MainCategory>(entity =>
        {
            entity.HasKey(e => e.MainCategoryId).HasName("PK__MainCate__0290BDB6EC9E08D8");

            entity.HasIndex(e => e.MainCategoryName, "UQ__MainCate__121AD3E306C01471").IsUnique();

            entity.Property(e => e.MainCategoryId).HasColumnName("MainCategoryID");
            entity.Property(e => e.MainCategoryName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.MainCategoryPrompt)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Order>(entity =>
        {
            entity.HasKey(e => e.OrderId).HasName("PK__Orders__C3905BAF0A70BB9B");

            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.BasicId).HasColumnName("BasicID");
            entity.Property(e => e.FinalPrompt).IsUnicode(false);
            entity.Property(e => e.OrderDate).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.UserId).HasColumnName("UserID");

            entity.HasOne(d => d.Basic).WithMany(p => p.Orders)
                .HasForeignKey(d => d.BasicId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__BasicID__68487DD7");

            entity.HasOne(d => d.Review).WithMany(p => p.Orders)
                .HasForeignKey(d => d.ReviewId)
                .HasConstraintName("FK__Orders__ReviewID__6A30C649");

            entity.HasOne(d => d.Status).WithMany(p => p.Orders)
                .HasForeignKey(d => d.StatusId)
                .HasConstraintName("FK__Orders__StatusID__693CA210");

            entity.HasOne(d => d.User).WithMany(p => p.Orders)
                .HasForeignKey(d => d.UserId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Orders__UserID__6754599E");
        });

        modelBuilder.Entity<OrdersItem>(entity =>
        {
            entity.HasKey(e => e.OrderItemId).HasName("PK__OrdersIt__57ED06A1C51DF2F0");

            entity.Property(e => e.OrderItemId).HasColumnName("OrderItemID");
            entity.Property(e => e.OrderId).HasColumnName("OrderID");
            entity.Property(e => e.ProductsId).HasColumnName("ProductsID");
            entity.Property(e => e.UserDescription)
                .HasMaxLength(400)
                .IsUnicode(false);

            entity.HasOne(d => d.BasicSitesPlatformsNavigation).WithMany(p => p.OrdersItems)
                .HasForeignKey(d => d.BasicSitesPlatforms)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdersIte__Basic__74AE54BC");

            entity.HasOne(d => d.Order).WithMany(p => p.OrdersItems)
                .HasForeignKey(d => d.OrderId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdersIte__Order__73BA3083");

            entity.HasOne(d => d.Products).WithMany(p => p.OrdersItems)
                .HasForeignKey(d => d.ProductsId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__OrdersIte__Produ__72C60C4A");
        });

        modelBuilder.Entity<Platform>(entity =>
        {
            entity.HasKey(e => e.PlatformId).HasName("PK__Platform__F559F6DA2A561587");

            entity.HasIndex(e => e.PlatformName, "UQ__Platform__85614BEEAA7B29F5").IsUnique();

            entity.Property(e => e.PlatformId).HasColumnName("PlatformID");
            entity.Property(e => e.PlatformName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PlatformsPrompt)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Product>(entity =>
        {
            entity.HasKey(e => e.ProductsId).HasName("PK__Products__BB48EDC5962DBDC4");

            entity.Property(e => e.ProductsId).HasColumnName("ProductsID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.ProductPrompt)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.ProductsName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);

            entity.HasOne(d => d.Category).WithMany(p => p.Products)
                .HasForeignKey(d => d.CategoryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Products__Catego__5165187F");
        });

        modelBuilder.Entity<Review>(entity =>
        {
            entity.HasKey(e => e.ReviewId).HasName("PK__Review__74BC79AEF132B175");

            entity.ToTable("Review");

            entity.Property(e => e.ReviewId).HasColumnName("ReviewID");
            entity.Property(e => e.ReviewImg)
                .HasMaxLength(150)
                .IsUnicode(false);
            entity.Property(e => e.ReviewText).IsUnicode(false);
        });

        modelBuilder.Entity<SiteType>(entity =>
        {
            entity.HasKey(e => e.SiteTypeId).HasName("PK__SiteType__85A71C864C409FE8");

            entity.Property(e => e.SiteTypeId).HasColumnName("SiteTypeID");
            entity.Property(e => e.DescreptionPrompt)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.NamePrompt)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.SiteTypeDescreption)
                .IsRequired()
                .HasMaxLength(300)
                .IsUnicode(false);
            entity.Property(e => e.SiteTypeName)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false);
        });

        modelBuilder.Entity<Status>(entity =>
        {
            entity.HasKey(e => e.StatusId).HasName("PK__Statuses__C8EE2043E6FFC866");

            entity.Property(e => e.StatusId).HasColumnName("StatusID");
            entity.Property(e => e.StatusName)
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<User>(entity =>
        {
            entity.HasKey(e => e.UserId).HasName("PK__Users__1788CCACA78FB6D4");

            entity.HasIndex(e => e.UserName, "UQ__Users__C9F28456F63D1056").IsUnique();

            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.BasicId).HasColumnName("BasicID");
            entity.Property(e => e.FirstName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LastName)
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.UserName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);

            entity.HasOne(d => d.Basic).WithMany(p => p.Users)
                .HasForeignKey(d => d.BasicId)
                .HasConstraintName("FK__Users__BasicID__619B8048");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}