// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class CartItem
{
    public short CartId { get; set; }

    public short UserId { get; set; }

    public short ProductsId { get; set; }

    public byte? Valid { get; set; }

    public string UserDescription { get; set; }

    public short BasicSitesPlatforms { get; set; }

    public virtual Platform BasicSitesPlatformsNavigation { get; set; }

    public virtual Product Products { get; set; }

    public virtual User User { get; set; }
}