// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Entities;

public partial class Order
{
    public short OrderId { get; set; }

    public DateOnly? OrderDate { get; set; }

    public double OrderSum { get; set; }

    public short UserId { get; set; }

    public short BasicId { get; set; }

    public string FinalPrompt { get; set; }

    public short? StatusId { get; set; }

    public short? ReviewId { get; set; }

    public virtual BasicSite Basic { get; set; }

    public virtual ICollection<OrdersItem> OrdersItems { get; set; } = new List<OrdersItem>();

    public virtual Review Review { get; set; }

    public virtual Status Status { get; set; }

    public virtual User User { get; set; }
}